import './global.css';
import { theme } from '../config/theme';
import { Container, CssBaseline, Paper, ThemeProvider } from '@mui/material';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { MenuAppBar } from '@libs/next-ui/components';
import { DrawerMenuList } from '../components/navigation';

export const metadata = {
  title: 'Welcome to front-app-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <MenuAppBar>
            <DrawerMenuList />
          </MenuAppBar>
          <Container component={Paper} fixed>
            {children}
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
